name: 'GitHub Actions Shell'
description: 'Open a reverse ssh connection from a GitHub Action.'
inputs:
  rssh_split_env:
    description: 'Whether to use the full env or separate variables. False by default.'
    required: false
    default: false
  rssh_env:
    description: 'The environment needed by the script.'
    required: false
    default: ''
  rssh_ssh_key:
    description: 'A private ssh key authorized on the relay server.'
    required: false
    default: ''
  rssh_relay_host:
    description: 'The relay ip / domain name.'
    required: false
    default: ''
  rssh_relay_user:
    description: 'The relay server user.'
    required: false
    default: ''
  rssh_relay_key:
    description: 'A relay host public key (the first from `ssh-keyscan $rssh_relay_host`)'
    required: false
    default: ''
  rssh_relay_port:
    description: 'The port used in the relay server for the ssh connection.'
    required: false
    default: '10022'

runs:
  using: "composite"
  steps:

    - name: Launch the connection script.
      run: |
        echo $RSSH_RELAY_USER
        cd ${{ github.action_path }}
        ./connect
      shell: bash
      env:
        RSSH_ENV: ${{ inputs.rssh_env }}
        RSSH_SSH_KEY: ${{ inputs.rssh_ssh_key }}
        RSSH_RELAY_HOST: ${{ inputs.rssh_relay_host }}
        RSSH_RELAY_USER: ${{ inputs.rssh_relay_user }}
        RSSH_RELAY_KEY: ${{ inputs.rssh_relay_key }}
        RSSH_RELAY_PORT: ${{ inputs.rssh_relay_port }}
