---
name: ci

on:

  push:
    branches:
      - "main"

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:

  test:
    name: test
    runs-on: ubuntu-latest

    steps:

      - name: Test the action with the env.
        uses: CarloDePieri/github_actions_shell@v1
        with:
          rssh_env: ${{ secrets.RSSH_ENV }}

      - name: Reset the continue file.
        run: rm -f /tmp/continue

      - name: Test the action without the env.
        uses: CarloDePieri/github_actions_shell@v1
        with:
          rssh_use_env: false
          rssh_ssh_key: ${{ secrets.RSSH_SSH_KEY }}
          rssh_relay_host: ${{ secrets.RSSH_RELAY_HOST }}
          rssh_relay_user: ${{ secrets.RSSH_RELAY_USER }}
          rssh_relay_key: ${{ secrets.RSSH_RELAY_KEY }}

      - name: Check the pwd.
        run: pwd
